image: gradle:alpine

variables:
  OSSRH_USERNAME: "$OSSRH_USERNAME"
  OSSRH_PASSWORD: "$OSSRH_PASSWORD"
  SIGNING_KEY: "$SIGNING_KEY"
  SIGNING_KEY_ID: $SIGNING_KEY_ID"
  SIGNING_PASSWORD: "$SIGNING_PASSWORD"
  SONATYPE_STAGING_PROFILE_ID: "$SONATYPE_STAGING_PROFILE_ID"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build-sdk:
  stage: build
  script:
    - ./gradlew :androidSDK:assembleRelease
only:
   - /^[0-9]+\.[0-9]+$/

publish-sdk-maven:
  stage: deploy
  script:
    - ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
only:
  - tags