# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :android do
	desc "Assemble shared XCFrameork"
	lane :miamcore do
 		gradle(
			task: "clean assembleReleaseXCFramework"
		)
		copy_artifacts(
 			target_path: "frameworks",
  			artifacts: ["miamCore/build/XCFrameworks/release/*.xcframework"]
		)
	end
end

platform :ios do
	lane :miamios do
		xcclean(scheme: 'Release')
		create_xcframework(
    		workspace: 'MiamIOSFramework.xcworkspace',
    		scheme: 'Release',
			product_name: "MiamIOSFramework",
    		destinations: ['iOS'],
    		xcframework_output_directory: 'frameworks/'
		)
	end
	lane :beta do
        ensure_git_status_clean
        increment_build_number(xcodeproj: "iosApp/iosApp.xcodeproj")
        commit_version_bump(
                xcodeproj: "iosApp/iosApp.xcodeproj",
                message: "Increment build number [ci skip]",
                force: true
        )
        match(type: "appstore", readonly: true)
    	build_app(workspace: "showRoom.xcworkspace", scheme: "iosApp")
    	upload_to_testflight
  	end
end	
