# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
	desc "Assemble shared XCFrameork"
	lane :releasexcframework do
 		gradle(
			task: "clean assembleReleaseXCFramework"
		)
		copy_artifacts(
 			target_path: "frameworks",
  			artifacts: ["shared/build/XCFrameworks/release/*.xcframework"]
		)
	end
end

platform :ios do
	lane :miamiosframework do
	end
end	
